let jokesArray = [
  `Why don’t scientists trust atoms? Because they make up everything!`,
  `Why did the scarecrow win an award? Because he was outstanding in his field!`,
  `I told my wife she was drawing her eyebrows too high. She looked surprised.`,
  `Why don’t skeletons fight each other? They don’t have the guts.`,
  `What do you call fake spaghetti? An impasta!`,
  `I would avoid the sushi if I were you. It’s a little fishy.`,
  `Want to hear a construction joke? Oh… never mind, I’m still working on that one.`,
  `Why do cows wear bells? Because their horns don’t work.`,
  `I’m reading a book on anti-gravity. It’s impossible to put down!`,
  `Did you hear about the guy who invented Lifesavers? He made a mint!`,
  `What do you call cheese that isn't yours? Nacho cheese.`,
  `Why did the tomato turn red? Because it saw the salad dressing!`,
  `Parallel lines have so much in common… It’s a shame they’ll never meet.`,
  `I used to play piano by ear, but now I use my hands.`,
  `How do you organize a space party? You planet.`,
  `Why was the math book sad? It had too many problems.`,
  `What’s orange and sounds like a parrot? A carrot.`,
  `How does a penguin build its house? Igloos it together.`,
  `Why don’t programmers like nature? Too many bugs.`,
  `I would tell you a UDP joke, but you might not get it.`,
  `Why do Java developers wear glasses? Because they don’t C#.`,
  `How do you comfort a JavaScript bug? You console it.`,
  `I told my computer I needed a break, and now it won’t stop sending me vacation ads.`,
  `Why did the computer go to therapy? It had a hard drive.`,
  `Why did the developer go broke? Because he used up all his cache.`,
  `I renamed my iPod The Titanic, so when I plug it in, it says 'The Titanic is syncing.'`,
  `What's a computer's favorite snack? Microchips.`,
  `Why did the function return early? It couldn’t handle the recursion.`,
  `What do you call a cat who loves coding? A purr-ogrammer.`,
  `What do you get when you cross a snake and a pie? A python.`,
  `Why can’t you trust stairs? They’re always up to something.`,
  `Did you hear about the kidnapping at school? It’s fine, he woke up.`,
  `What do you call a pile of cats? A meowtain.`,
  `Why did the golfer bring two pairs of pants? In case he got a hole in one.`,
  `What do you call an elephant that doesn’t matter? An irrelephant.`,
  `Why don't oysters donate to charity? Because they’re shellfish.`,
  `How do you find Will Smith in the snow? You look for fresh prints.`,
  `I couldn’t figure out why the baseball kept getting bigger. Then it hit me.`,
  `What did the grape do when he got stepped on? Nothing, he just let out a little wine.`,
  `Why did the bicycle fall over? It was two tired.`,
  `I used to hate facial hair… but then it grew on me.`,
  `I'm on a seafood diet. I see food and I eat it.`,
  `Why did the cookie cry? Because his mom was a wafer too long.`,
  `What kind of shoes do ninjas wear? Sneakers.`,
  `Why don’t some couples go to the gym? Because some relationships don’t work out.`,
  `I'm reading a book on the history of glue – I can’t seem to put it down.`,
  `Did you hear about the claustrophobic astronaut? He needed a little space.`,
  `What do you call a factory that makes okay products? A satisfactory.`,
  `Why did the man get hit by a bike every day? He was stuck in a vicious cycle.`,
  `I asked the librarian if the library had books on paranoia. She whispered, 'They're right behind you…'`,
  `What do you call a can opener that doesn’t work? A can’t opener.`,
  `Why did the chicken go to the séance? To talk to the other side.`,
  `Why don’t eggs tell jokes? They’d crack each other up.`,
  `What happens when you witness a shipwreck? You let it sink in.`,
  `I told my suitcase we wouldn’t be going on vacation this year. Now I’m dealing with emotional baggage.`,
  `Why was the broom late? It swept in.`,
  `Did you hear the rumor about butter? Well, I’m not going to spread it!`,
  `Why don’t ants get sick? Because they have tiny ant-bodies.`,
  `Why do bees have sticky hair? Because they use honeycombs.`,
  `Why did the student eat his homework? Because the teacher said it was a piece of cake!`,
  `Why are elevator jokes so classic? They work on many levels.`,
  `Why did the man run around his bed? Because he was trying to catch up on sleep.`,
  `Did you hear about the circus fire? It was in tents.`,
  `Why did the dog sit in the shade? Because he didn’t want to be a hot dog.`,
  `What do you call a snowman with a six-pack? An abdominal snowman.`,
  `How do you make holy water? You boil the hell out of it.`,
  `What did one wall say to the other? I’ll meet you at the corner.`,
  `What do you get when you cross a vampire with a snowman? Frostbite.`,
  `What did the janitor say when he jumped out of the closet? 'Supplies!'`,
  `Why don’t you ever see elephants hiding in trees? Because they’re so good at it.`,
  `How do cows stay up to date? They read the moos-paper.`,
  `What does a nosy pepper do? Gets jalapeño business!`,
  `What’s brown and sticky? A stick.`,
  `What did the zero say to the eight? Nice belt!`,
  `Why did the fish blush? Because it saw the ocean’s bottom.`,
  `How does a vampire start a letter? Tomb it may concern...`,
  `What lights up a soccer stadium? A soccer match.`,
  `Why was the calendar afraid? Its days were numbered.`,
  `I told a joke about a roof once… It went over everyone's head.`,
  `What did the banana say to the dog? Bananas can't talk!`,
  `Why did the belt go to jail? For holding up a pair of pants.`,
  `How do you catch a squirrel? Climb a tree and act like a nut!`,
  `Why was the computer cold? It left its Windows open.`,
  `Why did the web developer storm out of the restaurant? Because he couldn’t find the menu element.`,
  `What's a computer’s favorite beatle? Ringo... because it always loops.`,
  `Why couldn’t the leopard play hide and seek? Because he was always spotted.`,
  `What kind of music do balloons hate? Pop.`,
  `Why are frogs so happy? Because they eat whatever bugs them.`,
  `What did one hat say to the other? Stay here, I’m going on ahead.`,
  `How does a scientist freshen her breath? With experi-mints.`,
  `Why did the duck get a job? Because he was out of bills.`,
  `Why do pancakes always win at baseball? They have the best batter.`,
  `Why did the cat get kicked out of the computer lab? It kept chasing the mouse.`,
  `What’s the best way to watch a fly fishing tournament? Live stream.`,
  `I once got into a fight with a broken elevator… I took it to another level.`,
  `Why did the man bring a ladder to the bar? He heard the drinks were on the house.`,
  `What did the fisherman say to the magician? Pick a cod, any cod.`,
  `Why don’t mountains get cold in the winter? They wear snowcaps.`,
  `Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.`,
  `I used to be addicted to soap, but I’m clean now.`,
  `I don’t trust stairs. They’re always up to something.`
]



let arrayLength = jokesArray.length;
let num = Math.floor(Math.random() * arrayLength-1);

document.getElementById('btn').onclick = () =>{
     location.reload();
}

let p = document.createElement('p');
p.innerHTML = `<p>"${jokesArray[num]}"</p>`;
document.querySelector('.display').prepend(p);


// document.querySelector('.display').innerHTML = `<p>"${jokesArray[num]}"</p>`
